### ISSUE TITLE
组件路由文档内容不对应

### ISSUE THREAD

**Issue by tanggd** [hellof2e/quark-design-docs#9]
复现步骤：
1. 点击Header 组件，进入 https://quark-design.hellobike.com/#/zh-CN/component/button 页面；
2. 此时默认展示 vue 的。点击react，切换到react，进入 https://quark-design.hellobike.com/#/zh-CN/component/button-react 页面。
3. 再点击Header 组件，进入 https://quark-design.hellobike.com/#/zh-CN/component/button 页面；
至此就出现了路由文档不对应的bug，如图：
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/23456667/201956695-3a79773e-1487-4443-9c30-a2b5a378f216.png">

**Comment by xxxsf** [comment]
感谢反馈，回头空了修复下
